// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.SilverPrice
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("currency")]
        public string Currency { get; set; }

        [JsonProperty("gram")]
        public double Gram { get; set; }

        [JsonProperty("kilogram")]
        public double Kilogram { get; set; }

        [JsonProperty("ounce")]
        public double Ounce { get; set; }

        [JsonProperty("lastUpdated")]
        public long LastUpdated { get; set; }
    }
}
